---
title: "jf1_unsubscriber_jsg2145"
author: "Jared Garfinkel"
date: "8/19/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
url = "https://www.actionnetwork.org/subscriptions"

# anorg_html = GET(url)
# anorg_html
# warn_for_status(html_session(url))
# 
# subs = anorg_html %>% 
#   html_nodes(".subscription_name span span") %>% 
#   html_text()
# 
# anorg_sess = html_session(url) %>% 
#   follow_link(css = ".no_icon:nth-child(1) .js-fancylink")
# .subscription_name
# .clearfix
# .js-fancylink
# .no_icon:nth-child(1) .js-fancylink
```

```{r}
# url2 = "https://www.actionnetwork.org/dashboard"
# 
# anorg_html2 = GET(url2)
# 
# anorg2 = html(url2)
# 
# text = anorg2 %>% 
#   html_nodes("#navatar_wrap div div") %>% 
#   html_text()
# 
# anorg2_ss = html_session(url2) %>% 
#   follow_link(css = "#navatar_wrap")
# 
# subs = anorg2 %>% 
#   html_nodes("#navatar_wrap")
```

```{r}
url3 = "https://www.actionnetwork.org/users/sign_in"

anorg3_sess = session(url3)

?session

# anorg3_sess

# anorg3_sess %>%
#   read_html()
# anorg3_sess %>% 
#   html_element("#ipt-login") %>% 
#   html_form()

# ?html_form
# 
# anorg3_sess %>% 
#   read_html()
# 
# read_html(url3) %>% 
#   html_form() %>% 
#   .[[1]]

 # ?read_html
anorgform = html_form(anorg3_sess)[[1]]
# 
# read_html(anorg3_sess) %>% 
#   html_attr("#ipt-login")
# 
# html = read_html(url3)
# 
# ?html_form

# form3 = html_form(html)[[1]]
# 
# # html_text(html)
# 
# ?POST
# 
# get = GET(url3)
# 
# class(get)
# class(anorg3_sess)
# class(html)
# 
# html %>% 
#   html_elements("form")
# 
# html %>% 
#   html_elements("body")
# 
# html %>% 
#   html_elements("method")
# 
# anorg3_sess %>% 
#   html_elements("input") %>% 
#   html_text2() # blank
# 
# anorg3_sess %>% 
#   html_elements("head") %>% 
#   html_attrs()
# 
# anorg3_sess %>% 
#   html_elements("input") %>% 
#   html_attr("type") # weird stuff
# 
# anorg3_sess %>% 
#   html_elements("type") #blank
#   # html_attrs() # blank
# 
# ?html_element
##
# anorgform["fields"][[1]]["mac_addr"][[1]]$value # "c0:e4:34:7d:a1:55"
# 
# anorgform["fields"][[1]]["url"][[1]]$value # "http://www.actionnetwork.org/users/sign_in"
# 
# anorgform["fields"][[1]]["reason"][[1]]$value # "1"
# 
# anorgform["fields"][[c(1, 4)]]$value # "0"
##
# html_attr(anorgform)

# ?html_attrs

# anorg3_sess %>% 
#   read_html() %>% 
#   html_form()

# anorgform[5]$fields$reason

# ?html_form_set

filled_form <- html_form_set(anorgform, 
                             "mac_addr" = "c0:e4:34:7d:a1:55",
                             "url" = "http://www.actionnetwork.org/users/sign_in",
                             "reason" = "1", "0")

# filled_form <- anorgform %>% 
#   html_form_set("input" = "jacquelynjoan@gmail.com", "hidden"="Goldman222!")

session_submit(anorg3_sess, filled_form)

s = anorg3_sess %>%
  jump_to(url)

# class(s)
# 
# s

# s %>% 
#   # html_text() # doesn't work
#   # read_html() %>% # not what I want
#   html_elements(".subscription_name") %>% 
#   html_text()

m = html_form(s)[[1]]

# m["fields"][[1]]["mac_addr"][[1]]$value # "c0:e4:34:7d:a1:55"
# 
# m["fields"][[1]]["url"][[1]]$value # "http://www.actionnetwork.org/subscriptions"
# 
# m["fields"][[1]]["reason"][[1]]$value # "1"
# 
# m["fields"][[c(1, 4)]]$value # "0"

filled_form2 = html_form_set(anorgform, 
                             "mac_addr" = "c0:e4:34:7d:a1:55",
                             "url" = "https://www.actionnetwork.org/subscriptions",
                             "reason" = "1", "0")

session_submit(s, filled_form2)

s

n = s %>% 
  jump_to("https://www.actionnetwork.org/subscriptions")

# n %>% 
#   html_elements(".subscription_name")


u = NULL
for (i in 1:length(t)) {
  u[[i]] = s %>% html_nodes(paste0(".no_icon:nth-child(", i, ") .js-fancylink")) %>% html_attrs()
}
v = NULL
for (i in 1:length(u)) {
  v[[i]] = s %>% jump_to(paste0(url, u[[i]][[1]][["href"]]))
}
w = NULL
for (i in 1:length(v)) {
  w[[i]] = html_form(v[[1]])[[i]]
}

x = NULL
for (i in 1:length(w)) {
  submit_form(v[[i]], w[[i]], submit = "commit")
}
# 
# 
# u[[170]][[1]][["href"]]
# html_attrs(u[[1]])[[1]][["class"]]
# u[[1]]
# <a href="#unsubscribe_modal4288845" class="subscription_list_button button lined_button button_red fancylink js-fancylink">Unsubscribe</a>
```
